server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mymusicclub?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 127.0.0.1
    port: 6379
    password: 7895123
    #表示选的是几号库
    database: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      #设置最大容量稍大一些，防止容量过小导致音乐无法上传
      max-file-size: 30MB #最大文件容量
      max-request-size: 100MB #最大请求容量

mybatis:
  type-aliases-package: music.domain #设置mybatis全局别名
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
